version: '3.8'

services:
  server:
    build: ./server  # Path to server Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./shared:/app/shared
    environment:
      - DONT_USE_DOT_ENV=1
      - FLASK_ENV=development
      # Remote MySQL
      - MYSQL_REMOTE_HOST=message_queue_db
      - MYSQL_REMOTE_DATABASE=queue_db
      - MYSQL_REMOTE_USER=mysql_user
      - MYSQL_REMOTE_PASSWORD=securepassword
    depends_on:
      - scheduler
      - message_queue_db
    networks:
      - app-network

  scheduler:
    build: ./scheduler  # Path to server Dockerfile
    volumes:
      - ./shared:/app/shared
    environment:
      - DONT_USE_DOT_ENV=1
      - FLASK_ENV=development
      # Local MySQL
      - MYSQL_HOST=scheduler_db
      - MYSQL_DATABASE=scheduler_db
      - MYSQL_USER=scheduler_user
      - MYSQL_PASSWORD=securepassword
      # Remote MySQL
      - MYSQL_REMOTE_HOST=message_queue_db
      - MYSQL_REMOTE_DATABASE=queue_db
      - MYSQL_REMOTE_USER=mysql_user
      - MYSQL_REMOTE_PASSWORD=securepassword
      # articles MySQL
      - MYSQL_ARTICLES_HOST=REMOTE_HOST:3306
      - MYSQL_ARTICLES_DATABASE=storage_db
      - MYSQL_ARTICLES_USER=admin
      - MYSQL_ARTICLES_PASSWORD=securepassword
    depends_on:
      - scheduler_db
      - message_queue_db
    networks:
      - app-network

  app:
    build: ./app  # Path to app Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./app:/app
    environment:
      - REACT_APP_BE_ADDRESS=http://localhost:5050
      - CHOKIDAR_USEPOLLING=true  # To help with file system watching in Docker
    depends_on:
      - server

  scheduler_db:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: scheduler_db
      MYSQL_USER: scheduler_user
      MYSQL_PASSWORD: securepassword
    volumes:
      - scheduler_datadrive:/var/lib/mysql
    networks:
      - app-network

  message_queue_db:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: queue_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: securepassword
    volumes:
      - message_queue_datadrive:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  scheduler_datadrive:
  message_queue_datadrive:
